# Operadores, listas y vectores

# Tipos de datos básicos

- Numéricos
- Enteros
- Texto
- Booleanos

# Operadores aritméticos

## Suma

In [49]:
2 + 2

4

In [50]:
a = 10
b = 20
a + b

30

In [51]:
a + 100

110

## Resta

In [52]:
a - 200

-190

## Multiplicación

In [53]:
a * b

200

## División

In [54]:
a / b

0.5

## Potencia

In [94]:
2 ** 2

4

# Operadores de comparación

## Mayor que

In [56]:
a > b

False

In [57]:
a > 5

True

## Menor que

In [58]:
a < 10

False

## Mayor o igual que

In [59]:
a >= 10

True

## Menor o igual que

In [60]:
a <= 10

True

## Igualdad

In [61]:
a == b

False

In [62]:
a == a

True

## Diferencia (no igual)

In [63]:
a != b

True

In [64]:
2 != 3

True

# Listas (`[]`)

In [65]:
lista1 = [1, 2, 3]
lista1

[1, 2, 3]

In [66]:
lista2 = ["a", 20, True]
lista2

['a', 20, True]

In [67]:
type(lista1)

list

In [68]:
len(lista1)

3

In [87]:
# Error: no es posible sumar a los elementos de la lista el número 3
lista1 + 3

TypeError: can only concatenate list (not "int") to list

In [90]:
# Error: no es posible comparar los elementos de la lista con algún número o elemento de interés
lista1 > 2

TypeError: '>' not supported between instances of 'list' and 'int'

# Vectores (array 1D)

In [69]:
import numpy as np

In [70]:
vector1 = np.array(lista1)
vector1

array([1, 2, 3])

In [71]:
type(vector1)

numpy.ndarray

In [72]:
len(vector1)

3

In [88]:
# En los vectores sí es posible realizar operaciones aritméticas elemento a elemento
vector1 + 10

array([11, 12, 13])

In [92]:
# En los vectores sí es posible comparar los elementos 
vector1 > 2

array([False, False,  True])

In [73]:
# En los arrays no es posible mezclar los tipos de datos
vector2 = np.array([1, 2, 3, "a"])
vector2

array(['1', '2', '3', 'a'], dtype='<U11')

# Indexación (subconjuntos)

In [74]:
vector2[0]

'1'

In [75]:
vector2[-4]

'1'

In [76]:
# 0: incluyente
# 2: Excluyente
vector2[0:2]

array(['1', '2'], dtype='<U11')

In [77]:
# Desde el elemento 1 (incluyente) hasta el último elemento
vector2[1:]

array(['2', '3', 'a'], dtype='<U11')

In [78]:
# Desde el elemento 0 hasta el elemento 3 (excluyente)
vector2[:3]

array(['1', '2', '3'], dtype='<U11')

In [96]:
# Error porque está fuera de los límites
vector2[4]

IndexError: index 4 is out of bounds for axis 0 with size 4